import type { Metadata } from "next";
import { ErrorProvider } from "@/context/errorContext";
import { UserProvider } from "@/context/userContext";
import ToastContainer from "@/components/ui/toastContainer";


export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};



export default function RootLayout({children}: {children: React.ReactNode}) {
	return (
		<html lang="en">
			<body>
				<ErrorProvider>
					<ToastContainer />
					<UserProvider>
						{children}
					</UserProvider>
				</ErrorProvider>
			</body>
		</html>
	)
}
