import type { Metadata } from "next";
import { ErrorProvider } from "@/context/errorContext";
import ToastContainer from "@/components/ui/errorToast";
import { QueryProvider } from "@/context/queryProvider";
import "./globals.css"

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};


export default function RootLayout({children}: {children: React.ReactNode}) {
	return (
		<html lang="en">
			<body>
				<ErrorProvider>
					<ToastContainer />
					<QueryProvider>
						{children}
					</QueryProvider>
				</ErrorProvider>
			</body>
		</html>
	)
}
